server:
  port: 8089
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service  # Corrected URL format
    username: spring
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true